source $ZSH/oh-my-zsh.sh
source /opt/homebrew/opt/zsh-syntax-highlighting/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /opt/homebrew/opt/zsh-autosuggestions/share/zsh-autosuggestions/zsh-autosuggestions.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="true"

zstyle ':omz:update' mode auto

plugins=(git zsh-syntax-highlighting zsh-autosuggestions)

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

PS1="%F{green}%D{%H:%M:%S} %F{green}%~ %F{green}→ %f"

bindkey '^ ' autosuggest-accept
bindkey '^J' down-line-or-search
bindkey '^K' up-line-or-search
bindkey '^H' backward-char
bindkey '^L' forward-char
bindkey '^D' kill-whole-line

eval $(thefuck --alias f)
